name = "leaderboard-proxy"
account_id = "e48004d927a458b2c6e12c0604a73571"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "CROSSWORD_KV"
id = "0c2b29431e5046e5ae8ec65af56b5d45"
