using System.Globalization;
namespace SwedishCrossword.Api.Endpoints;

internal static class PuzzleEndpoints
{
    private const string DefaultPuzzleSize = "17x17";

    internal static WebApplication MapPuzzleEndpoints(this WebApplication app, string puzzlePath)
    {
        app.MapGet("/api/puzzle/today", async (string? size, SubmissionTokenService tokenService, TimeProvider timeProvider, PuzzleCache puzzleCache, CancellationToken ct) =>
        {
            var sizeKey = NormalisePuzzleSize(size);
            var today = timeProvider.GetSwedishDate();
            var todayFile = ResolvePuzzleFileForSize(puzzlePath, today, sizeKey);

            if (todayFile is not null)
            {
                var prepared = await puzzleCache.GetPreparedAsync(todayFile, today, ct);
                if (prepared is not null)
                {
                    var token = tokenService.GenerateToken(prepared.PuzzleHash, prepared.CellCount, today.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture));
                    var result = prepared.StrippedJsonTemplate.Replace("\"__TOKEN__\"", $"\"{token}\"", StringComparison.Ordinal);
                    return Results.Content(result, "application/json; charset=utf-8");
                }
            }

            // Puzzle is generated by PuzzleWarmupService at startup; not ready yet
            return Results.Json(new ErrorResponse("Puzzle not ready yet"), statusCode: StatusCodes.Status503ServiceUnavailable);
        }).CacheOutput("puzzle-today");

        app.MapGet("/api/puzzle/{date}", async (string date, string? size, SubmissionTokenService tokenService, TimeProvider timeProvider, PuzzleCache puzzleCache, CancellationToken ct) =>
        {
            if (!DateOnly.TryParseExact(date, "yyyy-MM-dd", out var parsedDate))
                return Results.BadRequest(new ErrorResponse("Invalid date format. Use yyyy-MM-dd"));

            // Only allow access to today's or past puzzles
            if (parsedDate > timeProvider.GetSwedishDate())
                return Results.NotFound(new ErrorResponse("No puzzle available for the requested date"));

            var sizeKey = NormalisePuzzleSize(size);
            var puzzleFile = ResolvePuzzleFileForSize(puzzlePath, parsedDate, sizeKey);

            if (puzzleFile is not null)
            {
                var prepared = await puzzleCache.GetPreparedAsync(puzzleFile, parsedDate, ct);
                if (prepared is not null)
                {
                    var token = tokenService.GenerateToken(prepared.PuzzleHash, prepared.CellCount, parsedDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture));
                    var result = prepared.StrippedJsonTemplate.Replace("\"__TOKEN__\"", $"\"{token}\"", StringComparison.Ordinal);
                    return Results.Content(result, "application/json; charset=utf-8");
                }
            }

            return Results.NotFound(new ErrorResponse("No puzzle available for the requested date"));
        }).CacheOutput("puzzle-archive");

        app.MapPost("/api/puzzle/check", async (PuzzleCheckRequest body, SubmissionTokenService tokenService, PuzzleCache puzzleCache, CancellationToken ct) =>
        {
            if (string.IsNullOrWhiteSpace(body.Token))
                return Results.Json(new ErrorResponse("Missing token"), statusCode: 403);

            if (string.IsNullOrWhiteSpace(body.PuzzleDate) ||
                !DateOnly.TryParseExact(body.PuzzleDate, "yyyy-MM-dd", out var puzzleDate))
                return Results.BadRequest(new ErrorResponse("Invalid puzzle date"));

            var basicValidation = tokenService.ValidateAccess(body.Token);
            if (!basicValidation.IsValid)
                return Results.Json(new ErrorResponse(basicValidation.Error ?? "Validation failed"), statusCode: 403);

            var filePath = ResolvePuzzleFile(puzzlePath, body.PuzzleDate, body.Size);
            if (filePath is null)
                return Results.NotFound(new ErrorResponse("Puzzle not found"));

            var prepared = await puzzleCache.GetPreparedAsync(filePath, puzzleDate, ct);
            if (prepared is null)
                return Results.Json(new ErrorResponse("Failed to read puzzle data"), statusCode: 500);

            var validation = tokenService.ValidateAccess(
                body.Token,
                prepared.PuzzleHash,
                puzzleDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture));
            if (!validation.IsValid)
                return Results.Json(new ErrorResponse(validation.Error ?? "Validation failed"), statusCode: 403);

            var answers = await puzzleCache.GetAnswersAsync(filePath);
            if (answers is null)
                return Results.Json(new ErrorResponse("Failed to read puzzle data"), statusCode: 500);

            var results = new Dictionary<string, bool>();
            var allCorrect = true;
            var allFilled = true;

            foreach (var (key, answer) in answers)
            {
                if (body.Cells.TryGetValue(key, out var submitted) && !string.IsNullOrEmpty(submitted))
                {
                    var correct = string.Equals(submitted, answer, StringComparison.OrdinalIgnoreCase);
                    results[key] = correct;
                    if (!correct) allCorrect = false;
                }
                else
                {
                    results[key] = false;
                    allCorrect = false;
                    allFilled = false;
                }
            }

            return Results.Ok(new { solved = allCorrect && allFilled, results });
        }).RequireRateLimiting("puzzle-interact");

        app.MapPost("/api/puzzle/hint", async (PuzzleHintRequest body, SubmissionTokenService tokenService, PuzzleCache puzzleCache, CancellationToken ct) =>
        {
            if (string.IsNullOrWhiteSpace(body.Token))
                return Results.Json(new ErrorResponse("Missing token"), statusCode: 403);

            if (string.IsNullOrWhiteSpace(body.PuzzleDate) ||
                !DateOnly.TryParseExact(body.PuzzleDate, "yyyy-MM-dd", out var puzzleDate))
                return Results.BadRequest(new ErrorResponse("Invalid puzzle date"));

            if (body.Cells is not { Length: > 0 } || body.Cells.Length > 300)
                return Results.BadRequest(new ErrorResponse("Invalid cells"));

            var basicValidation = tokenService.ValidateAccess(body.Token);
            if (!basicValidation.IsValid)
                return Results.Json(new ErrorResponse(basicValidation.Error ?? "Validation failed"), statusCode: 403);

            var filePath = ResolvePuzzleFile(puzzlePath, body.PuzzleDate, body.Size);
            if (filePath is null)
                return Results.NotFound(new ErrorResponse("Puzzle not found"));

            var prepared = await puzzleCache.GetPreparedAsync(filePath, puzzleDate, ct);
            if (prepared is null)
                return Results.Json(new ErrorResponse("Failed to read puzzle data"), statusCode: 500);

            var validation = tokenService.ValidateAccess(
                body.Token,
                prepared.PuzzleHash,
                puzzleDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture));
            if (!validation.IsValid)
                return Results.Json(new ErrorResponse(validation.Error ?? "Validation failed"), statusCode: 403);

            var answers = await puzzleCache.GetAnswersAsync(filePath);
            if (answers is null)
                return Results.Json(new ErrorResponse("Failed to read puzzle data"), statusCode: 500);

            var letters = new Dictionary<string, string>();
            foreach (var cell in body.Cells)
            {
                if (cell.Length != 2) continue;
                var key = $"{cell[0]},{cell[1]}";
                if (answers.TryGetValue(key, out var letter))
                    letters[key] = letter;
            }

            return Results.Ok(new { letters });
        }).RequireRateLimiting("puzzle-interact");

        app.MapGet("/api/puzzle/dates", (TimeProvider timeProvider, PuzzleDateIndex dateIndex) =>
        {
            var today = timeProvider.GetSwedishDate();
            var result = dateIndex.GetDates(today);
            return Results.Ok(result);
        }).CacheOutput("puzzle-dates");

        app.MapGet("/api/puzzle/hashes", async (string? date, TimeProvider timeProvider, PuzzleCache puzzleCache, CancellationToken ct) =>
        {
            var target = DateOnly.TryParseExact(date, "yyyy-MM-dd", out var parsed)
                ? parsed
                : timeProvider.GetSwedishDate();

            var mapping = new Dictionary<string, string>();
            foreach (var sizeKey in PuzzleWarmupService.ValidSizeKeys)
            {
                var file = ResolvePuzzleFileForSize(puzzlePath, target, sizeKey);
                if (file is null) continue;
                var prepared = await puzzleCache.GetPreparedAsync(file, target, ct);
                if (prepared is not null)
                    mapping[sizeKey] = prepared.PuzzleHash;
            }

            return Results.Ok(mapping);
        }).CacheOutput("puzzle-dates");

        return app;
    }

    private static string NormalisePuzzleSize(string? size)
    {
        if (string.IsNullOrWhiteSpace(size)) return DefaultPuzzleSize;
        // Legacy compat: "small" → "10x10"
        if (string.Equals(size, "small", StringComparison.OrdinalIgnoreCase)) return "10x10";
        if (PuzzleWarmupService.ValidSizeKeys.Contains(size)) return size;
        return DefaultPuzzleSize;
    }

    private static string? ResolvePuzzleFileForSize(string basePath, DateOnly date, string sizeKey)
    {
        // New naming: puzzle-{date}-{size}.json
        var path = Path.Combine(basePath, $"puzzle-{date:yyyy-MM-dd}-{sizeKey}.json");
        if (File.Exists(path)) return path;

        // Legacy naming: puzzle-{date}.json (17x17) and puzzle-{date}-small.json (10x10)
        if (string.Equals(sizeKey, "17x17", StringComparison.Ordinal))
        {
            var legacy = Path.Combine(basePath, $"puzzle-{date:yyyy-MM-dd}.json");
            if (File.Exists(legacy)) return legacy;
        }
        else if (string.Equals(sizeKey, "10x10", StringComparison.Ordinal))
        {
            var legacy = Path.Combine(basePath, $"puzzle-{date:yyyy-MM-dd}-small.json");
            if (File.Exists(legacy)) return legacy;
        }

        // Fall back to default size
        if (!string.Equals(sizeKey, DefaultPuzzleSize, StringComparison.Ordinal))
        {
            var fallback = Path.Combine(basePath, $"puzzle-{date:yyyy-MM-dd}-{DefaultPuzzleSize}.json");
            if (File.Exists(fallback)) return fallback;
            var legacyFallback = Path.Combine(basePath, $"puzzle-{date:yyyy-MM-dd}.json");
            if (File.Exists(legacyFallback)) return legacyFallback;
        }

        return null;
    }

    private static string? ResolvePuzzleFile(string puzzlePath, string puzzleDate, string? size)
    {
        if (!DateOnly.TryParseExact(puzzleDate, "yyyy-MM-dd", out var parsed))
            return null;
        return ResolvePuzzleFileForSize(puzzlePath, parsed, NormalisePuzzleSize(size));
    }
}
