namespace SwedishCrossword.Api;

internal static class PuzzleEndpoints
{
    private const string DefaultPuzzleSize = "17x17";

    internal static WebApplication MapPuzzleEndpoints(this WebApplication app, string puzzlePath)
    {
        app.MapGet("/api/puzzle/today", async (string? size, SubmissionTokenService tokenService, TimeProvider timeProvider) =>
        {
            var sizeKey = NormalisePuzzleSize(size);
            var today = DateOnly.FromDateTime(timeProvider.GetUtcNow().UtcDateTime);
            var todayFile = ResolvePuzzleFileForSize(puzzlePath, today, sizeKey);

            if (todayFile is not null)
            {
                var json = await File.ReadAllTextAsync(todayFile);
                return Results.Content(tokenService.InjectToken(json, today), "application/json; charset=utf-8");
            }

            // Puzzle is generated by PuzzleWarmupService at startup; not ready yet
            return Results.Json(new ErrorResponse("Puzzle not ready yet"), statusCode: StatusCodes.Status503ServiceUnavailable);
        }).CacheOutput("puzzle-today");

        app.MapGet("/api/puzzle/{date}", async (string date, string? size, SubmissionTokenService tokenService, TimeProvider timeProvider) =>
        {
            if (!DateOnly.TryParseExact(date, "yyyy-MM-dd", out var parsedDate))
                return Results.BadRequest(new ErrorResponse("Invalid date format. Use yyyy-MM-dd"));

            // Only allow access to today's or past puzzles
            if (parsedDate > DateOnly.FromDateTime(timeProvider.GetUtcNow().UtcDateTime))
                return Results.NotFound(new ErrorResponse("No puzzle available for the requested date"));

            var sizeKey = NormalisePuzzleSize(size);
            var puzzleFile = ResolvePuzzleFileForSize(puzzlePath, parsedDate, sizeKey);

            if (puzzleFile is not null)
            {
                var json = await File.ReadAllTextAsync(puzzleFile);
                return Results.Content(tokenService.InjectToken(json, parsedDate), "application/json; charset=utf-8");
            }

            return Results.NotFound(new ErrorResponse("No puzzle available for the requested date"));
        }).CacheOutput("puzzle-archive");

        app.MapPost("/api/puzzle/check", (PuzzleCheckRequest body, SubmissionTokenService tokenService) =>
        {
            if (string.IsNullOrWhiteSpace(body.Token))
                return Results.Json(new ErrorResponse("Missing token"), statusCode: 403);

            if (string.IsNullOrWhiteSpace(body.PuzzleDate) ||
                !DateOnly.TryParseExact(body.PuzzleDate, "yyyy-MM-dd", out _))
                return Results.BadRequest(new ErrorResponse("Invalid puzzle date"));

            var validation = tokenService.ValidateAccess(body.Token);
            if (!validation.IsValid)
                return Results.Json(new ErrorResponse(validation.Error), statusCode: 403);

            var filePath = ResolvePuzzleFile(puzzlePath, body.PuzzleDate, body.Size);
            if (filePath is null)
                return Results.NotFound(new ErrorResponse("Puzzle not found"));

            var answers = SubmissionTokenService.ReadAnswers(filePath);
            if (answers is null)
                return Results.Json(new ErrorResponse("Failed to read puzzle data"), statusCode: 500);

            var results = new Dictionary<string, bool>();
            var allCorrect = true;
            var allFilled = true;

            foreach (var (key, answer) in answers)
            {
                if (body.Cells.TryGetValue(key, out var submitted) && !string.IsNullOrEmpty(submitted))
                {
                    var correct = string.Equals(submitted, answer, StringComparison.OrdinalIgnoreCase);
                    results[key] = correct;
                    if (!correct) allCorrect = false;
                }
                else
                {
                    results[key] = false;
                    allCorrect = false;
                    allFilled = false;
                }
            }

            return Results.Ok(new { solved = allCorrect && allFilled, results });
        }).RequireRateLimiting("puzzle-interact");

        app.MapPost("/api/puzzle/hint", (PuzzleHintRequest body, SubmissionTokenService tokenService) =>
        {
            if (string.IsNullOrWhiteSpace(body.Token))
                return Results.Json(new ErrorResponse("Missing token"), statusCode: 403);

            if (string.IsNullOrWhiteSpace(body.PuzzleDate) ||
                !DateOnly.TryParseExact(body.PuzzleDate, "yyyy-MM-dd", out _))
                return Results.BadRequest(new ErrorResponse("Invalid puzzle date"));

            if (body.Cells is not { Length: > 0 } || body.Cells.Length > 300)
                return Results.BadRequest(new ErrorResponse("Invalid cells"));

            var validation = tokenService.ValidateAccess(body.Token);
            if (!validation.IsValid)
                return Results.Json(new ErrorResponse(validation.Error), statusCode: 403);

            var filePath = ResolvePuzzleFile(puzzlePath, body.PuzzleDate, body.Size);
            if (filePath is null)
                return Results.NotFound(new ErrorResponse("Puzzle not found"));

            var answers = SubmissionTokenService.ReadAnswers(filePath);
            if (answers is null)
                return Results.Json(new ErrorResponse("Failed to read puzzle data"), statusCode: 500);

            var letters = new Dictionary<string, string>();
            foreach (var cell in body.Cells)
            {
                if (cell.Length != 2) continue;
                var key = $"{cell[0]},{cell[1]}";
                if (answers.TryGetValue(key, out var letter))
                    letters[key] = letter;
            }

            return Results.Ok(new { letters });
        }).RequireRateLimiting("puzzle-interact");

        app.MapGet("/api/puzzle/dates", (TimeProvider timeProvider) =>
        {
            var today = DateOnly.FromDateTime(timeProvider.GetUtcNow().UtcDateTime);
            var files = Directory.GetFiles(puzzlePath, "puzzle-*.json");

            // Collect unique dates and which sizes are available for each
            var dateSizes = new Dictionary<string, HashSet<string>>();
            foreach (var f in files)
            {
                var name = Path.GetFileNameWithoutExtension(f).Replace("puzzle-", "");
                // New format: yyyy-MM-dd-WxH  Legacy: yyyy-MM-dd or yyyy-MM-dd-small
                string datePart;
                string sizeKey;
                if (name.Length > 10 && name[10] == '-')
                {
                    datePart = name[..10];
                    var sizePart = name[11..];
                    sizeKey = string.Equals(sizePart, "small", StringComparison.OrdinalIgnoreCase) ? "10x10" : sizePart;
                }
                else
                {
                    datePart = name;
                    sizeKey = "17x17";
                }

                if (!DateOnly.TryParseExact(datePart, "yyyy-MM-dd", out var parsed) || parsed > today)
                    continue;

                if (!dateSizes.TryGetValue(datePart, out var sizes))
                {
                    sizes = [];
                    dateSizes[datePart] = sizes;
                }
                sizes.Add(sizeKey);
            }

            var result = dateSizes
                .OrderByDescending(kv => kv.Key)
                .Select(kv => new { date = kv.Key, sizes = kv.Value.OrderBy(s => s).ToArray() })
                .ToArray();

            return Results.Ok(result);
        }).CacheOutput("puzzle-dates");

        return app;
    }

    private static string NormalisePuzzleSize(string? size)
    {
        if (string.IsNullOrWhiteSpace(size)) return DefaultPuzzleSize;
        // Legacy compat: "small" → "10x10"
        if (string.Equals(size, "small", StringComparison.OrdinalIgnoreCase)) return "10x10";
        if (PuzzleWarmupService.ValidSizeKeys.Contains(size)) return size;
        return DefaultPuzzleSize;
    }

    private static string? ResolvePuzzleFileForSize(string basePath, DateOnly date, string sizeKey)
    {
        // New naming: puzzle-{date}-{size}.json
        var path = Path.Combine(basePath, $"puzzle-{date:yyyy-MM-dd}-{sizeKey}.json");
        if (File.Exists(path)) return path;

        // Legacy naming: puzzle-{date}.json (17x17) and puzzle-{date}-small.json (10x10)
        if (string.Equals(sizeKey, "17x17", StringComparison.Ordinal))
        {
            var legacy = Path.Combine(basePath, $"puzzle-{date:yyyy-MM-dd}.json");
            if (File.Exists(legacy)) return legacy;
        }
        else if (string.Equals(sizeKey, "10x10", StringComparison.Ordinal))
        {
            var legacy = Path.Combine(basePath, $"puzzle-{date:yyyy-MM-dd}-small.json");
            if (File.Exists(legacy)) return legacy;
        }

        // Fall back to default size
        if (!string.Equals(sizeKey, DefaultPuzzleSize, StringComparison.Ordinal))
        {
            var fallback = Path.Combine(basePath, $"puzzle-{date:yyyy-MM-dd}-{DefaultPuzzleSize}.json");
            if (File.Exists(fallback)) return fallback;
            var legacyFallback = Path.Combine(basePath, $"puzzle-{date:yyyy-MM-dd}.json");
            if (File.Exists(legacyFallback)) return legacyFallback;
        }

        return null;
    }

    private static string? ResolvePuzzleFile(string puzzlePath, string puzzleDate, string? size)
    {
        if (!DateOnly.TryParseExact(puzzleDate, "yyyy-MM-dd", out var parsed))
            return null;
        return ResolvePuzzleFileForSize(puzzlePath, parsed, NormalisePuzzleSize(size));
    }
}
